/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TODOApp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class TODOApp {

    public static void main(String[] args) {

        ApplicationContext ApplicationContext = SpringApplication.run(TODOApp.class);

        System.out.println("Hello, World!");
    }
}
