/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class TodoApp {

    public static void main(String[] args) {

        SpringApplication.run(TODOApp.class);

        System.out.println("Hello, World!");
    }
}
